// generated from rosidl_generator_c/resource/idl.h.em
// with input from v2x_msgs:msg/AdverseWeatherConditionExtremeWeatherConditionSubCauseCode.idl
// generated code does not contain a copyright notice

#ifndef V2X_MSGS__MSG__ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_H_
#define V2X_MSGS__MSG__ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_H_

#include "v2x_msgs/msg/detail/adverse_weather_condition_extreme_weather_condition_sub_cause_code__struct.h"
#include "v2x_msgs/msg/detail/adverse_weather_condition_extreme_weather_condition_sub_cause_code__functions.h"
#include "v2x_msgs/msg/detail/adverse_weather_condition_extreme_weather_condition_sub_cause_code__type_support.h"

#endif  // V2X_MSGS__MSG__ADVERSE_WEATHER_CONDITION_EXTREME_WEATHER_CONDITION_SUB_CAUSE_CODE_H_
